default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  port: <%= ENV.fetch("POSTGRES_PORT", 5433) %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "postgres") %>

development:
  <<: *default
  database: family_archive_development

test:
  <<: *default
  database: family_archive_test

production:
  <<: *default
  database: family_archive_production
  username: <%= ENV.fetch("POSTGRES_USER", "family_archive") %>
  password: <%= ENV["FAMILY_ARCHIVE_DATABASE_PASSWORD"] %>
